# Site settings
title: Garin's Blog
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bo Yang
user_description: 7年 C/C++ arm/x86平台研发经验，基础扎实，强独立分析，解决问题的能力；熟悉主流的RPC通信框架，曾参与 tizen sef框架及log框架的设计与研发；熟悉分布式系统设计、开发；熟悉 python、shell等脚本语言及MYSQL数据库设计；性格开朗、适应力强，有着较强的组织沟通能力；
user_title: Software Developer
email: garin.yang@outlook.com
twitter_username: garin.yang
github_username:  garin.yang
gplus_username:  garin.yang

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
